### ISSUE TITLE
Connexion error on Android 6.0.X

### ISSUE THREAD

**Issue by koikic** [DoubangoTelecom/imsdroid#582]
Hello dude!!
I got an error when try to register with your lib. 
The error occurs in your method **initialize2()** in your class NgnEngine.Java, more precisely at the line where you call _**System.loadLibrary("tinyWRAP_neon");**_ . 
My device is under Android 6.0.1. 
Find hereuder the error code. Thank You !!

06-17 11:03:10.564 30327-30327/com.example.christianjs.spitchee E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.christianjs.spitchee, PID: 30327
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.example.christianjs.spitchee-1/lib/arm/libtinyWRAP_neon.so: has text relocations
at java.lang.Runtime.loadLibrary(Runtime.java:372)
at java.lang.System.loadLibrary(System.java:1076)
**at org.doubango.ngn.NgnEngine.initialize2(NgnEngine.java:110)
at org.doubango.ngn.NgnEngine.<clinit>(NgnEngine.java:94)**
at com.example.christianjs.spitchee.PhoneManager.start(PhoneManager.java:88)
at com.example.christianjs.spitchee.UserConnected.onStart(UserConnected.java:78)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
at android.app.Activity.performStart(Activity.java:6268)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5422)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by koikic** [comment]
Resolved by setting **"targetSdkVersion =  23"** to **"targetSdkVersion = 22"** in manifest file

**Comment by gang018** [comment]
For those, who need to use 23 SDK version - you need to grant at runtime RECORD_AUDIO permission. After that all will work fine

**Comment by behelit** [comment]
Even if you target 22, the error is still shown to users on 24+ (7.0)

> Detected problems with app native libraries
> (please consult the log for detail):
> libtinyWRAP_neon.so: text relocations

**Comment by zaferaydn** [comment]
for those who wants to target 23, what if we force using libtinyWRAP.so insead of libtinyWRAP_neon.so?

**Comment by honeynatividad** [comment]
Anyone encountered an error using targetSdkVersion >22.?
